### ISSUE TITLE
Skapa entiteter, context och repos för ProductProvider

### ISSUE THREAD

**Issue by EVettainen** [Project-Rika/Rika_ProductProvider#1]
# Tasks

### ProductEntity
- ProductId (PK)
- ProductName
- ProductPrice
- ProductSalePrice
- ProductDescription

- ProductCategoryId (FK)
- ProductCategory

- ProductSize - nullable?
- ProductColor - nullable?

### ProductDbContext
- [x] Implementera en DbContext för Products

### Konfigurera databaskoppling
- [x] Skapa migration och uppdatera databas

### Skapa secret för autentisering 
- [x] Se till att skapa en secret för autetinserings-delen
