### ISSUE TITLE
En product provider ska kunna skicka in en produkt-model som sedan lagras i en databas

### ISSUE THREAD

**Issue by EVettainen** [Project-Rika/Rika_ProductProvider#4]
![Image](https://github.com/user-attachments/assets/a898673e-a6a4-45e4-9eb9-23b1695d8ba6)
## Tasks

- [x] Bygg funktionalitet för att kunna lagra en produkt-entitet i en databas
 
- [x] Mappa modellen som kommer från klienten 
  - Packa upp objektet
  - Placera värdena från modellen i product-entiten
  - Kontrollera nullvärden

- [x] Lagra objektet i databasen
  - Skicka in entiteten så att den sparas
  - Returnera statuskod beroende på utfall till klienten

## Acceptanskriterier
1. Klienten ska kunna lagra en produkt i databasen
2. Skicka tillbaka rätt statuskod beroende på utfall t.ex: Badrequest, OK etc.

### **Lyckad lagring**
  - Förutsättningar: En produkt-modell har skickats in från klienten
  - Denna innehåller alla värden
          
**Steg**
  - Ta emot objekt från klient
  - Mappa objektet i entiteten för produkt
  - Spara i databas
           
**Förväntat resultat**
  - En produkt sparas i databasen och statuskod 201 returneras till klient

### **Nullvärden finns**
  - Förutsättningar: En produkt-modell har skickats in från klienten

**Steg**
  - Klient har begärt att en produkt-modell lagras i databasen
  - Modellen har nullvärden på tvingande värden

**Förväntat resultat**
  - Statuskod 400 returneras och informerar klienten vilket värde som är tvingande
