### ISSUE TITLE
En product provider ska kunna få ut en lista av produkter från databasen

### ISSUE THREAD

**Issue by EVettainen** [Project-Rika/Rika_ProductProvider#5]
![Image](https://github.com/user-attachments/assets/3c9542cf-0d2e-453f-a033-d640b328cf36)

## Tasks

- [x] Kontrollera kriterierna som klienten önskat
  - Använd dig av en linq-query för att hitta önskade produkter i databasen

- [x] Hämta produkter ur databas
  - Se till att ha rätt autentisering för att kopplas till databasen
  - Filtrera produkterna i databasen efter önskemål från klient
  - Placera produkter i en lista

- [x] Returnera statuskod samt lista till klienten
  - Listan ska vara läsbar för klienten
  - Klienten ska få en statuskod returnerad

## Acceptanskriterier
1. Klienten ska kunna filtrera efter specifika produkter
2. Statuskoder ska skickas med vid varje fall
3. Listan som skickas tillbaka ska vara läsbar för klienten

### **Lyckad hämtning**
  - Förutsättningar: En lista av produkter har begärts från klienten
          
**Steg**
  - En lista av produkter har begärts från en klient
  - Filtrera efter kategori, pris etc
  - Returnera Listan
           
**Förväntat resultat**
  - En lista som är sorterad efter önskemål är returnerad till klienten med en statuskod 200

### **Finns inget att hämta**
  - Förutsättningar: En lista av produkter har begärts från klienten

**Steg**
  - En lista av produkter har begärts från en klient men klienten har filtrerat på kategorier där produkter inte finns

**Förväntat resultat**
  - Statuskod 404 returneras och informerar klienten att det finns inga produkter att hämta
