### ISSUE TITLE
En product provider ska kunna hitta en produkt i databasen

### ISSUE THREAD

**Issue by EVettainen** [Project-Rika/Rika_ProductProvider#6]
![Image](https://github.com/user-attachments/assets/6cf9c5b8-49f2-4d78-a68f-bc5dcbf19cf9)

## Tasks

- [ ] Kontrollera kriterierna som klienten önskat
  - Använd dig av en linq-query för att hitta önskad produkt i databasen

- [ ] Hämta produkt ur databas
  - Se till att ha rätt autentisering för att kopplas till databasen
  - Filtrera efter produkten i databasen efter önskemål från klient

- [ ] Returnera statuskod samt produkt till klienten
  - Produkten ska returnernas efter hur modellen ser ut
  - Klienten ska få en statuskod returnerad

## Acceptanskriterier
1. Klienten ska kunna hitta en specifik produkt efter filtrering
2. Statuskoder ska skickas med vid varje fall

### **Lyckad hämtning**
  - Förutsättningar: En specifik produkt har begärts från klienten
          
**Steg**
  - En lista av produkter har begärts från en klient
  - Filtrera efter kategori, pris etc
  - Returnera Listan
           
**Förväntat resultat**
  - En lista som är sorterad efter önskemål är returnerad till klienten med en statuskod 200

### **Finns inget att hämta**
- Förutsättningar: En specifik produkt har begärts från klienten

**Steg**
  - En produkt har begärts från en klient men klienten har filtrerat på kategorier där produkter inte finns

**Förväntat resultat**
  - Statuskod 404 returneras och informerar klienten att det finns ingen produkt att hämta
