### ISSUE TITLE
En product provider ska kunna uppdatera en befintlig produkt i databasen

### ISSUE THREAD

**Issue by EVettainen** [Project-Rika/Rika_ProductProvider#7]
![Image](https://github.com/user-attachments/assets/b333dc27-fb2a-41d1-a6b5-0722647b4416)
## Tasks

- [ ] Hitta matchande produkt i databas
  - Se till att ha rätt autentisering för att kopplas till databasen
  - Använd produkt-id på produkten klienten begärt för att hitta denna i databasen

- [ ] Mappa om produkten från databasen mot de uppdaterade värdena från klienten
  - Se till att modellerna matchar
  - Se till att inga nullvärden finns på tvingande värden

- [ ] Uppdatera databasen
- [ ] Skicka tillbaka rätt statuskod baserat på olika fall

## Acceptanskriterier
1. Rätt produkt ska hittas i databasen efter klientens önskemål
2. Produkten ska kunna uppdateras efter klientens önskemål
3. Databasen måste uppdateras

### **Lyckad uppdatering**
  - Förutsättningar: Klienten vill uppdatera en produkt
          
**Steg**
  - En specifik produkt har fått ändrade värden från klienten
  - Sök upp rätt produkt via produkt-id:t
  - Uppdatera produkten
  - Uppdatera databasen
           
**Förväntat resultat**
  - En produkt har fått uppdaterade värden som klienten har begärt och en statuskod 200 har returnerats

### **Misslyckad uppdatering**
  - Förutsättningar: Klienten vill uppdatera en produkt
          
**Steg**
  - En specifik produkt har fått ändrade värden från klienten
  - Sök upp rätt produkt via produkt-id:t
  - Klient har missat ett eller flera tvingande värden
           
**Förväntat resultat**
  - En produkt har försökts uppdateras men värden har missats returnerar statuskod 400

### **Finns inget att uppdatera**
  - Förutsättningar: Klienten vill uppdatera en produkt

**Steg**
  - Klienten vill uppdatera en produkt som inte finns

**Förväntat resultat**
  - Statuskod 404 returneras och informerar klienten att det finns ingen produkt att uppdatera
