### ISSUE TITLE
En product provider ska kunna ta bort en produkt från databasen

### ISSUE THREAD

**Issue by EVettainen** [Project-Rika/Rika_ProductProvider#8]
## Tasks

- [x] Hitta matchande produkt i databas
  - Använd produkt-id på produkten klienten begärt för att hitta denna i databasen

- [x] Skapa funktionalitet för att radera produkten ur databasen
- [x] Uppdatera databasen
- [x] Skicka tillbaka rätt statuskod baserat på olika fall

## Acceptanskriterier
1. Rätt produkt ska hittas i databasen efter klientens önskemål
2. Produkten ska raderas ur databasen
3. Databasen ska uppdateras
4. Rätt statuskod ska skickas till klient

### **Lyckad radering**
  - Förutsättningar: Klienten vill radera en produkt
          
**Steg**
  - En specifik produkt har önskats att raderas
  - Sök upp rätt produkt via produkt-id:t
  - Radera produkten
  - Uppdatera databasen
           
**Förväntat resultat**
  - En produkt har raderats från databasen och en statuskod 200 har returnerats

### **Finns inget att radera**
  - Förutsättningar: Klienten vill radera en produkt

**Steg**
  - Klienten vill radera en produkt som inte finns

**Förväntat resultat**
  - Statuskod 404 returneras och informerar klienten att det finns ingen produkt att radera
